import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { ArtifactList } from "./ArtifactList";
import { useArtifactStore, type ArtifactInfo } from "../../stores/artifactStore";

export function ArtifactViewer() {
  const [selected, setSelected] = useState<ArtifactInfo | null>(null);
  const { selectedContent, fetchArtifactContent } = useArtifactStore();

  const handleSelect = async (artifact: ArtifactInfo) => {
    setSelected(artifact);
    // Extract agent ID from path (format: vaults/{agent}/research/...)
    const parts = artifact.path.split("/");
    const agentId = parts.length > 1 ? parts[0] : "";
    await fetchArtifactContent(agentId, artifact.path);
  };

  return (
    <div className="h-full flex flex-col">
      <div className="px-6 py-4 border-b border-neutral">
        <div className="flex items-center gap-3">
          {selected && (
            <button onClick={() => setSelected(null)} className="btn btn-ghost btn-xs">
              &larr;
            </button>
          )}
          <div>
            <h1 className="text-xl font-bold text-base-content">
              {selected ? selected.name : "Artifacts"}
            </h1>
            <p className="text-xs text-base-content/60 mt-1">
              {selected ? selected.description : "Research deliverables generated by agents"}
            </p>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        <div className="max-w-3xl mx-auto">
          {selected ? (
            <ArtifactContent content={selectedContent} artifact={selected} />
          ) : (
            <ArtifactList onSelect={handleSelect} />
          )}
        </div>
      </div>
    </div>
  );
}

function ArtifactContent({
  content,
  artifact,
}: {
  content: string | null;
  artifact: ArtifactInfo;
}) {
  if (content === null) {
    return (
      <div className="flex items-center justify-center h-32">
        <span className="loading loading-spinner loading-md text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Metadata bar */}
      <div className="flex items-center gap-2 text-xs text-base-content/60">
        <span className="badge badge-xs badge-ghost">{artifact.type}</span>
        {artifact.created && <span>{artifact.created}</span>}
        {artifact.tags.map((t) => (
          <span key={t} className="badge badge-xs badge-outline">{t}</span>
        ))}
      </div>

      {/* Rendered content */}
      <article className="prose prose-sm max-w-none">
        <ReactMarkdown>{content}</ReactMarkdown>
      </article>
    </div>
  );
}
